CREATE TABLE SYSTEMINIT (
	SYSTEMSTARTUP 	DATETIME 	NOT NULL,
	SYSTEMENDTIME 	DATETIME 	NOT NULL,
	IPHOST 			VARCHAR(50) NOT NULL
);
ALTER TABLE SYSTEMINIT ADD CONSTRAINT PK_SYSTEMINIT PRIMARY KEY (SYSTEMSTARTUP);

CREATE TABLE SCHEDULE (
	SCHEDULEID 		VARCHAR(50) 	NOT NULL,
	DESCI 			VARCHAR(500) 	NOT NULL,
	PROCESSCLASS 	VARCHAR(50) 	NOT NULL,
	INITIAL 		DATETIME 		NOT NULL,
	intervalTime 	INTEGER 		NOT NULL,
	CONFIG 			VARCHAR(500) 	NOT NULL,
	LOCKTIME 		DATETIME 		NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE SCHEDULE ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY (SCHEDULEID);