CREATE TABLE TABLELASTMODIFY (
	TABLE_NAME				VARCHAR(50) 	NOT NULL,
	TABLE_MODIFY_TIME		DATETIME		NOT NULL
);
ALTER TABLE TABLELASTMODIFY ADD CONSTRAINT PK_TABLELASTMODIFY PRIMARY KEY (TABLE_NAME);

CREATE TABLE SYSTEMINIT (
	SYSTEM_START_UP 	DATETIME 	NOT NULL, -- system start date time
	SYSTEM_END_TIME 	DATETIME 	NOT NULL, -- system shut down date time 
	IPHOST 				VARCHAR(50) NOT NULL
);
ALTER TABLE SYSTEMINIT ADD CONSTRAINT PK_SYSTEMINIT PRIMARY KEY (SYSTEM_START_UP);

CREATE TABLE SCHEDULE (
	SCHEDULE_ID 	VARCHAR(50) 	NOT NULL,	-- schedule id
	DESCI 			VARCHAR(500) 		NULL,
	PROCESS_CLASS 	VARCHAR(50) 	NOT NULL,	-- schedule java class(package + class name)
	INITIAL 		DATETIME 		NOT NULL, 	-- 
	INTERVA_TYPE	VARCHAR(5) 		NOT NULL,	-- DAY, MIN
	INTERVAL_TIME 	INTEGER 		NOT NULL,	-- 1 min or 1 day
	CONFIG 			VARCHAR(500) 		NULL,
	LOCK_TIME 		DATETIME 			NULL,	-- mark process start time
	ADDRESS			VARCHAR(500)		NULL,	-- mark process address
	LAST_MODI_TIME	DATETIME 		NOT NULL
);

ALTER TABLE SCHEDULE ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY (SCHEDULE_ID);

CREATE OR ALTER TRIGGER SCHEDULE_INS ON SCHEDULE FOR INSERT AS
BEGIN
	DECLARE @t_LastModify  datetime;
	UPDATE SCHEDULE SET XF_LASTMODTIME = getdate() FROM inserted WHERE inserted.SCHEDULEID = SCHEDULE.SCHEDULEID;

	SELECT @t_LastModify= xf_lastmodifytime FROM XF_TABLELASTMODIFY WHERE xf_tablename = 'SCHEDULE'; 
	if ( @t_LastModify  < getdate()  )
	BEGIN
		UPDATE XF_TABLELASTMODIFY SET xf_lastmodifytime =DATEADD( SECOND, 2,  getdate() ) WHERE xf_tablename = 'SCHEDULE'; 
	END
END